
package com.exemple.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws.exemple.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @return
     *     returns java.util.List<com.exemple.ws.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://ws.exemple.com/", className = "com.exemple.ws.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://ws.exemple.com/", className = "com.exemple.ws.GetComptesResponse")
    @Action(input = "http://ws.exemple.com/BanqueService/getComptesRequest", output = "http://ws.exemple.com/BanqueService/getComptesResponse")
    public List<Compte> getComptes();

    /**
     * 
     * @param code
     * @return
     *     returns com.exemple.ws.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://ws.exemple.com/", className = "com.exemple.ws.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://ws.exemple.com/", className = "com.exemple.ws.GetCompteResponse")
    @Action(input = "http://ws.exemple.com/BanqueService/getCompteRequest", output = "http://ws.exemple.com/BanqueService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        Long code);

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConversionEuroToDH")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionEuroToDH", targetNamespace = "http://ws.exemple.com/", className = "com.exemple.ws.ConversionEuroToDH")
    @ResponseWrapper(localName = "ConversionEuroToDHResponse", targetNamespace = "http://ws.exemple.com/", className = "com.exemple.ws.ConversionEuroToDHResponse")
    @Action(input = "http://ws.exemple.com/BanqueService/ConversionEuroToDHRequest", output = "http://ws.exemple.com/BanqueService/ConversionEuroToDHResponse")
    public double conversionEuroToDH(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

}
